# Глава_4_Основы_Numpy

In [ ]:
#ndarray, быстрый и потребляющий мало памяти многомерный массив, 
#предоставляющий векторные арифметические операции и возможность укладывания

#Стандартные математические функции для выполнения быстрых операций 
#над целыми массивами без явного выписывания циклов

#Средства для чтения массива данных с диска и записи его на диск, 
#а также для работы с проецируемыми на память файлами

#Алгоритмы линейной алгебры, генерация случайных чисел и преобразование Фурье

#Средства для интеграции с кодом, написанным на С, С++ или Fortran 

In [ ]:
#В большинстве приложений для анализа данных основной интерес представляет следующая функциональность: 

#массивы и векторные вычисления 

#быстрые векторные операции для переформатирования и очистки данных, выборки подмножеств и фильтрации, 
#преобразований и других видов вычислений; 

#стандартные алгоритмы работы с массивами, например: фильтрация, удаление дубликатов и теоретико-множественные операции; 

#эффективная описательная статистика, агрегирование и обобщение данных; 

#выравнивание данных и реляционные операции объединения и соединения разнородных наборов данных; 

#описание условной логики в виде выражений-массивов вместо циклов с ветвлением i f-eli f-else; 

#групповые операции с данными ( агрегирование, преобразование, применение функции).  

# NumPy ndarray: объект многомерного массива 

In [ ]:
#объект ndarray для представления N-мерного массива; 
#это быстрый и гибкий контейнер для хранения больших наборов данных в Python. 
#Массивы позволяют выполнять математические операции над целыми блоками данных, 
#применяя такой же синтаксис, как для соответствующих операций над скалярами

In [ ]:
#ndarray - это обобщенный многомерный контейнер для однородных данных, 
#т. е. в нем могут храниться только элементы одного типа. 
#У любого массива есть атрибут shape - кортеж, описывающий размер по каждому измерению, 
#и атрибут dtype - объект, описывающий тип данных в массиве

# Создание ndarray 

In [5]:
#Проще всего создать массив с помощью функции array. 
#Она принимает любой объект, похожий на последовательность (в том числе другой массив), 
#и порождает новый массив NнmPy, содержащий переданные данные. 
#Например, такое преобразование можно проделать со списком
import numpy as np
data1 = [6, 7, 5, 8, 0, 1]
arr1 = np.array(datal) 

In [6]:
arr1

array([6, 7, 5, 8, 0, 1])

In [7]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] 
arr2 = np.array(data2) 

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
#число осей
arr2.ndim 

2

In [10]:
arr2.shape 

(2, 4)

In [12]:
arr1.dtype 

dtype('int32')

In [13]:
arr2.dtype 

dtype('int32')

In [ ]:
#Помимо np. array, существует еще ряд функций для создания массивов. 
#Например, zeros и ones создают массивы заданной длины, состоящие из нулей и единиц соответственно, 
#а shape. empty создает массив, не инициализируя его элементы.

In [15]:
#Для создания многомерных массивов нужно передать кортеж, описывающий форму
np.zeros(10)
    

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(( 3, 6)) 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [20]:
#Функция arange - вариант встроенной в Python функции range, только возвращаемым значением является массив
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
#Поскольку NшnPy ориентирован, прежде всего, на численные расчеты, 
#тип данных, если он не указан явно, во многих случаях предполагается float64 

In [ ]:
#array - Преобразует входные данные (список, кортеж, массив или любую другую последовательность) в ndarray. 
#Тип dtype задается явно или выводится неявно. Входные данные по умолчанию копируются 

In [ ]:
#asarray - Преобразует входные данные в ndarray, но не копирует, если на вход уже подан ndarray 

In [ ]:
#arange - Аналогична встроенной функции range, но возвращает массив, а не список 

In [ ]:
#ones, ones like - Порождает массив, состоящий из одних единиц, с заданными атрибутами shape и dtype. 
#Функция ones_like принимает другой массив и порождает массив из одних единиц с такими же значениями shape и dtype

In [ ]:
#zeros, zeros like   - Аналогичны ones и ones_like, только порождаемый массив состоит из одних нулей 

In [ ]:
#empty, empty _like  - Создают новые массивы, выделяя под них память, но, в отличие от ones и zeros, не инициализируют ее 

In [ ]:
#еуе, identity - Создают единичную квадратную матрицу N х N (элементы на главной диагонали равны 1, все остальные - О) 